[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/evidence-hub package.json libs/shared"

[[context.production.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[[context.deploy-preview.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[[context.develop.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[dev]
    targetPort = 4312
    autoLaunch = false
    base = "/"
    command = "npx nx run evidence-hub:serve"

[[redirects]]
    from = "/fn/:operation"
    to = "/.netlify/functions/redis?operation=:operation"
    status = 200